[analysis]
# inference_dir = "/glade/derecho/scratch/jshen/pruning-turbulence-vit/base/inferences_chunked/"
inference_dir = "/glade/derecho/scratch/jshen/pruning-turbulence-vit/base/model/inferences"
output_dir = "/glade/derecho/scratch/jshen/pruning-turbulence-vit/base/model/long_analysis"
img_size = 256

analysis_length = 750000
temporal_mean = false
zonal_mean = false
zonal_eof_pc = false
eof_ncomp = 3
PC_autocorr_nlags = 300
div = true
spectra = false
return_period = false
return_period_anomaly = false # ?
PDF_U = false # ? 
PDF_Omega = false # ? 
