[analysis]
inference_dir = "/glade/derecho/scratch/jshen/prune_base/l1/inferences/25/"
output_dir = "/glade/derecho/scratch/jshen/prune_base/l1/long_analyses/25/"
img_size = 256

analysis_length = 750000
temporal_mean = true
zonal_mean = true
zonal_eof_pc = true
eof_ncomp = 3
PC_autocorr_nlags = 300
div = true
spectra = true
return_period = true
return_period_anomaly = false # ?
PDF_U = false
PDF_Omega = false
