checkpoint_file = "/glade/derecho/scratch/jshen/pruning-turbulence-vit/re_vit_0/checkpoints/best.tar"
output_dir = "/glade/derecho/scratch/jshen/pruning-turbulence-vit/re_vit_0_taylor/"

[pruning]
importance_metric = 'taylor'
prune_schedule = [0.08, 0.08, 0.08, 0.08, 0.08, 0.08, 0.08, 0.08]
epoch_schedule = [128,  128,  128,  128,  128,  128,  128,  128]

[finetuning]
restart_optimizer = true
batch_size = 16
lr = 0.00002
weight_decay = 1e-6
warmup_start_factor = 0.01
warmup_epochs = 2
plateau_factor = 0.5
plateau_patience = 3
early_stop_lr_threshold = 1e-6
