output_dir = '/glade/derecho/scratch/jshen/pruning-turbulence-vit/unet16_1f/'

[model]
model_type = "UNet"
img_size = 256
num_frames = 1
base_channels = 16
depth = 4

[train_dataset]
data_dir = '/glade/derecho/scratch/dpatel/2DTurbData/results/Re5000_fkx0fky4_r0.1_b20/NoSGS/NX256/dt0.0002_IC1'
frame_range = [ [200000, 210000], [995000, 1004997], ]
target_step = 3
input_step = 3
stride = 1
num_frames = 1

[validation_dataset]
data_dir = '/glade/derecho/scratch/dpatel/2DTurbData/results/Re5000_fkx0fky4_r0.1_b20/NoSGS/NX256/dt0.0002_IC1'
frame_range = [ [310000, 312000], ]
target_step = 3
input_step = 3
stride = 1
num_frames = 1

[training]
lr = 0.0005
weight_decay = 1e-7
warmup_start_factor = 0.001
warmup_epochs = 3
plateau_factor = 0.5
plateau_patience = 5
epochs = 1000
batch_size = 32
checkpoint_period = 50
